"use client";
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang === 'en' || savedLang === 'th') {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object') {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

const translations = {
  en: {
    // Common
    common: {
      home: 'Home',
      about: 'About',
      services: 'Services',
      contact: 'Contact',
      getQuote: 'Get Quote',
      trackShipment: 'Track Shipment',
      login: 'Login',
      logout: 'Logout',
      submit: 'Submit',
      cancel: 'Cancel',
      close: 'Close',
      save: 'Save',
      delete: 'Delete',
      edit: 'Edit',
      view: 'View',
      search: 'Search',
      loading: 'Loading...',
      welcome: 'Welcome',
    },
    // Home page
    home: {
      hero: 'Your Trusted Partner in Asia-Wide Logistics',
      subtitle: 'Seamless shipping solutions connecting Thailand to every corner of Asia',
      slide1Title: 'Global Logistics Solutions',
      slide1Subtitle: 'Connecting your business to the world with seamless air and sea freight services',
      slide2Title: 'Reliable and Fast Delivery',
      slide2Subtitle: '99.5% on-time delivery rate across 200+ ports and airports worldwide',
      slide3Title: 'Worldwide Cargo Network',
      slide3Subtitle: 'Trusted by businesses globally for their shipping and logistics needs',
      whyChoose: 'Why Choose Asian Shipping Thailand?',
      trackYourShipment: 'Track Your Shipment',
      enterTracking: 'Enter your tracking number',
      track: 'Track',
      ourServices: 'Our Services',
      testimonials: 'What Our Clients Say',
      readyToShip: 'Ready to Ship?',
      getStarted: 'Get started with our reliable logistics solutions today',
      contactUsToday: 'Contact us today and experience world-class logistics solutions with competitive pricing',
      contactUsNow: 'Contact Us Now',
      shipmentsDelivered: 'Shipments Delivered',
      countriesServed: 'Countries Served',
      yearsExperience: 'Years of Experience',
      satisfactionRate: 'Satisfaction Rate',
      secureTitle: 'Secure & Safe',
      secureDesc: 'Advanced security measures and insurance coverage for peace of mind',
      trackingTitle: 'Real-Time Tracking',
      trackingDesc: 'Monitor your shipments 24/7 with our advanced tracking system',
      supportTitle: 'Expert Support',
      supportDesc: 'Dedicated customer service team available around the clock',
      coverageTitle: 'Global Coverage',
      coverageDesc: '200+ ports and airports across Asia and beyond',
      globalNetwork: 'Our Global Network',
      partnerNetwork: 'Partner Network Across 5 Continents',
      airFreight: 'Air Freight',
      airFreightDesc: 'Fast and reliable air cargo services with competitive rates',
      seaFreightFCL: 'Sea Freight FCL',
      seaFreightFCLDesc: 'Full container load shipping for large volumes',
      seaFreightLCL: 'Sea Freight LCL',
      seaFreightLCLDesc: 'Cost-effective less than container load service',
      warehousing: 'Warehousing',
      warehousingDesc: 'Secure storage and inventory management solutions',
      weeklyFlights: 'Weekly Flights',
      globalPorts: 'Global Ports',
      happyClients: 'Happy Clients',
      onTimeRate: 'On-Time Rate',
      expressDelivery: 'Express Delivery',
      realTimeTracking: 'Real-time Tracking',
      customsSupport: 'Customs Support',
      containerOptions: 'Container Options',
      competitiveRates: 'Competitive Rates',
      globalNetworkFeature: 'Global Network',
      flexibleScheduling: 'Flexible Scheduling',
      consolidation: 'Consolidation',
      weeklyDepartures: 'Weekly Departures',
      security247: '24/7 Security',
      climateControl: 'Climate Control',
      inventoryTracking: 'Inventory Tracking',
      comprehensiveSolutions: 'Comprehensive logistics solutions tailored to your business needs',
      viewAllServices: 'View All Services',
      industryLeading: 'Industry-leading logistics solutions with unmatched reliability',
      learnMoreAboutUs: 'Learn More About Us',
      callUs: 'Call Us',
      emailUs: 'Email Us',
      businessHours: 'Business Hours',
      monFri: 'Mon-Fri: 9AM - 6PM',
      sat: 'Sat: 10AM - 2PM',
      sun: 'Sun: Closed',
    },
    // Services
    services: {
      airfreight: 'Air Freight',
      airfreightDesc: 'Fast and reliable air cargo services across Asia',
      fcl: 'Full Container Load (FCL)',
      fclDesc: 'Complete container shipping for large volumes',
      lcl: 'Less than Container Load (LCL)',
      lclDesc: 'Cost-effective shipping for smaller cargo',
      customs: 'Customs Clearance',
      customsDesc: 'Expert handling of all customs documentation',
      warehousing: 'Warehousing',
      warehousingDesc: 'Secure storage and distribution services',
      insurance: 'Cargo Insurance',
      insuranceDesc: 'Comprehensive coverage for your shipments',
    },
    // Contact
    contact: {
      getInTouch: 'Get In Touch',
      requestQuote: 'Request a Quote',
      name: 'Your Name',
      email: 'Email',
      phone: 'Phone Number',
      company: 'Company Name',
      service: 'Service Needed',
      selectService: 'Select a service',
      message: 'Message',
      sendMessage: 'Send Message',
      contactInfo: 'Contact Information',
      officeHours: 'Office Hours',
      mondayFriday: 'Monday - Friday: 9:00 AM - 6:00 PM',
      saturday: 'Saturday: 9:00 AM - 1:00 PM',
      sunday: 'Sunday: Closed',
      helpLogistics: "We're here to help with all your logistics needs",
    },
    // Portal
    portal: {
      customerPortal: 'Customer Portal',
      myShipments: 'My Shipments',
      trackShipment: 'Track Shipment',
      profile: 'Profile',
      settings: 'Settings',
      shipmentDetails: 'Shipment Details',
      status: 'Status',
      origin: 'Origin',
      destination: 'Destination',
      weight: 'Weight',
      eta: 'Estimated Arrival',
      viewTracking: 'View Tracking',
    },
    // Admin Portal
    admin: {
      adminPortal: 'Admin Portal',
      dashboard: 'Dashboard',
      manageShipments: 'Manage Shipments',
      addShipment: 'Add Shipment',
      customerQuotes: 'Customer Quotes',
      documents: 'Documents',
      database: 'Database',
      totalShipments: 'Total Shipments',
      activeShipments: 'Active Shipments',
      recentQuotes: 'Recent Quotes',
      quoteRequests: 'Quote Requests',
      recentEmails: 'Recent Emails',
      composeEmail: 'Compose Email',
      newRequests: 'New Requests',
      responded: 'Responded',
      pending: 'Pending',
      remove: 'Remove',
      removeSelected: 'Remove Selected',
      permanentDelete: 'Permanent Delete',
      viewRawJson: 'View Raw JSON Data',
    },
    // Tracking
    tracking: {
      trackYourShipment: 'Track Your Shipment',
      trackingNumber: 'Tracking Number',
      shipmentNotFound: 'Shipment not found',
      trackingHistory: 'Tracking History',
      current: 'CURRENT',
      serviceType: 'Service Type',
      bookingDate: 'Booking Date',
      estimatedDelivery: 'Estimated Delivery',
    },
    // About Page
    about: {
      title: 'About Asian Shipping Thailand',
      subtitle: "Thailand's trusted logistics partner for freight forwarding and customs brokerage since 2002.",
      yearsExp: 'Years Experience',
      regionalFocus: 'Regional Focus',
      fastCustoms: 'Fast Customs Clearance',
      deliveryGuarantee: 'Delivery Guarantee',
      ourStory: 'Our Story',
      storyP1: 'Founded in 2002, Asian Shipping (Thailand) Co., Ltd. began with a simple mission: to make international shipping accessible and reliable for businesses of all sizes. What started as a small freight forwarding operation in Bangkok has grown into a trusted logistics partner serving clients across Asia and beyond.',
      storyP2: 'As a qualified customs broker in Thailand, we specialize in clearing both general and dangerous cargo. Our expertise in air, sea, and ground transportation services, combined with our one-day delivery guarantee for import shipments, makes us the fastest service provider among local forwarders.',
      storyP3: "We're not just moving boxes—we're your logistics partner, committed to fast and reliable declaration, seamless door-to-door services, and ensuring your business operations run smoothly across Thailand and Asia.",
      certificationsTitle: 'Certifications & Memberships',
      certificationsSubtitle: 'Trusted, certified, and qualified to serve you',
      certifications: 'Certifications',
      customsBrokerage: 'Customs Brokerage',
      customsDesc: 'Asian Shipping (Thailand) Co., Ltd. is also a qualified customs broker in Thailand. We are specialized in clearing both general cargo and dangerous cargo. One day delivery for import shipments and one day declaration for export.',
      customsMission: 'FAST & RELIABLE DECLARATION IS OUR MISSION',
      doorToDoor: 'Door to Door Services & Inland Transportation',
      doorToDoorDesc: 'Due to our best performance in customs brokerage, we are trusted to be the fastest door to door service provider in Thailand among local forwarders. Asian guarantees a one day delivery to all customers in Thailand.',
      oneDayGuarantee: 'One Day Delivery Guarantee in Thailand',
      meetTeam: 'Meet Our Team',
      teamSubtitle: 'Experienced professionals dedicated to your success',
      coreValues: 'Our Core Values',
      valuesSubtitle: 'The principles that guide everything we do',
      reliability: 'Reliability',
      reliabilityDesc: 'We deliver on our promises with consistent, dependable service you can count on.',
      speed: 'Speed',
      speedDesc: 'Fast processing and transit times to keep your business moving forward.',
      security: 'Security',
      securityDesc: 'Your cargo is protected with comprehensive insurance and secure handling.',
      partnership: 'Partnership',
      partnershipDesc: 'We work as your logistics partner, not just a service provider.',
      readyToShip: 'Ready to Ship with Us?',
      joinBusiness: 'Join thousands of businesses that trust asianshippingthai for their shipping needs',
      getStarted: 'Get Started',
      viewServices: 'View Services',
    },
    // Services Pages
    servicesPage: {
      ourServices: 'Our Services',
      professionalFreight: 'Professional freight forwarding solutions',
      contactUs: 'Contact Us',
      exploreFeat: 'Explore Features',
      airfreightServices: 'Airfreight Services',
      fastReliableAir: 'Fast & Reliable Air Cargo',
      deliverWorldwide: 'We deliver cargo worldwide with speed and precision through our extensive network of air carriers.',
      seafreightFCL: 'Seafreight Services: FCL',
      fullContainerLoad: 'Full Container Load',
      fullContainerShipping: 'Full-container shipping service for large-scale sea freight with flexible options.',
      seafreightLCL: 'Seafreight Services: LCL',
      lessThanContainer: 'Less Than Container Load',
      costEffectiveSea: 'Cost-effective sea freight solution perfect for smaller shipments.',
      expressDelivery: 'Express Delivery',
      realTimeTracking: 'Real-time Tracking',
      customsClearance: 'Customs Clearance',
      doorToDoorService: 'Door-to-Door Service',
      containers2040: '20ft & 40ft Containers',
      competitiveRates: 'Competitive Rates',
      globalNetwork: 'Global Network',
      dedicatedSupport: 'Dedicated Support',
      costEffective: 'Cost-Effective',
      flexibleScheduling: 'Flexible Scheduling',
      consolidation: 'Consolidation',
      weeklyDepartures: 'Weekly Departures',
      learnMore: 'Learn More',
    },
    // Airfreight Page
    airfreight: {
      title: 'Airfreight Services',
      subtitle: 'Fast, reliable air cargo solutions with full visibility and expert customs handling.',
      whyShipByAir: 'Why ship by air with us',
      expressEconomy: 'Express & Economy',
      expressDesc: 'Next-flight-out, express, and deferred options to fit your budget and timeline.',
      liveTracking: 'Live Tracking',
      liveTrackingDesc: 'Real-time milestone updates from pickup to delivery with proactive alerts.',
      customsClearance: 'Customs Clearance',
      customsDesc: 'End-to-end documentation and brokerage to keep things moving at the border.',
      doorToDoor: 'Door-to-Door',
      doorToDoorDesc: 'Pickup, linehaul, and last-mile arranged seamlessly by our team.',
      serviceOptions: 'Service Options',
      serviceOptionsDesc: 'We offer flexible service profiles: Next-Flight-Out, Express, Standard, and Deferred. Whether you prioritize speed or cost, our team will plan the optimal routing and carrier mix for your cargo.',
      serviceList1: 'Pickup, consolidation, airline booking, and last-mile delivery',
      serviceList2: 'Dangerous goods handling and documentation support',
      serviceList3: 'Temperature-controlled options upon request',
      serviceList4: 'Insurance coverage and Proof of Delivery (POD)',
      whatWeHandle: 'What we handle',
      electronics: 'Electronics & Components',
      apparel: 'Apparel & Textiles',
      automotive: 'Automotive Parts',
      medical: 'Medical & Pharma',
      perishables: 'Perishables & Beverages',
      industrial: 'Industrial Tools & Machinery',
      documents: 'Documents & High-Value Items',
      transitTimes: 'Typical Transit Times',
      asiaUSAEU: 'Asia ➜ USA/EU',
      asiaUSAEUTime: '2 - 5 days',
      asiaUSAEUNote: 'Direct & consolidated services',
      intraAsia: 'Intra-Asia',
      intraAsiaTime: '1 - 3 days',
      intraAsiaNote: 'High frequency departures',
      asiaMiddleEast: 'Asia ➜ Middle East',
      asiaMiddleEastTime: '2 - 4 days',
      asiaMiddleEastNote: 'Strong hub connectivity',
      transitNote: 'Note: Transit times are estimates and may vary by carrier and season.',
      readyToMove: 'Ready to move your cargo?',
      tellUsAbout: "Tell us about your shipment and we'll provide the best airfreight solution.",
    },
    // FCL Page
    fcl: {
      title: 'FCL (Full Container Load)',
      subtitle: 'Reliable full-container ocean solutions with weekly schedules and competitive rates.',
      whyChooseFCL: 'Why choose FCL with us',
      containers: '20\' & 40\' Containers',
      containersDesc: 'Standard, High-Cube, and Special Equipment based on cargo needs.',
      globalNetwork: 'Global Network',
      globalNetworkDesc: 'Reliable weekly sailings with leading carriers and strong port coverage.',
      flexibleRouting: 'Flexible Routing',
      flexibleRoutingDesc: 'Direct, transshipment, and premium services for time-sensitive cargo.',
      secureHandling: 'Secure Handling',
      secureHandlingDesc: 'Sealed container security and optional cargo insurance.',
      containerOptions: 'Container Options',
      container20: '20\' Standard',
      container40: '40\' Standard',
      container40HC: '40\' High Cube',
      specialEquipment: 'Special Equipment',
      openTopFlatRack: 'Open Top / Flat Rack',
      approx: 'Approx.',
      includedServices: 'Included Services',
      service1: 'Pickup, stuffing, VGM, documentation, and export clearance',
      service2: 'Carrier booking and space protection during peak seasons',
      service3: 'Destination DO/ISF support and delivery coordination',
      service4: 'Insurance options and shipment visibility',
      transitTimes: 'Typical Transit Times',
      asiaUSAWC: 'Asia ➜ USA (WC)',
      asiaUSAWCTime: '14 - 20 days',
      asiaUSAWCNote: 'Direct sailings to West Coast',
      asiaUSAEC: 'Asia ➜ USA (EC)',
      asiaUSAECTime: '25 - 35 days',
      asiaUSAECNote: 'Via Panama or Suez',
      asiaEurope: 'Asia ➜ Europe',
      asiaEuropeTime: '25 - 35 days',
      asiaEuropeNote: 'Mainline carriers and alliances',
      transitNote: 'Note: Transit times vary by carrier, port congestion, and season.',
      contactForFCL: 'Contact Us for FCL',
      tellUsOrigin: 'Tell us your origin, destination, and container size to get started.',
    },
    // LCL Page
    lcl: {
      title: 'LCL (Less than Container)',
      subtitle: 'Cost-effective ocean freight for smaller loads with dependable weekly schedules.',
      whyShipLCL: 'Why ship LCL with us',
      sharedSpace: 'Shared Space, Lower Cost',
      sharedSpaceDesc: 'Pay only for the space you use with reliable weekly consolidation.',
      secureConsolidation: 'Secure Consolidation',
      secureConsolidationDesc: 'Careful handling at origin CFS with clear labeling and packing standards.',
      extensiveLanes: 'Extensive Lanes',
      extensiveLanesDesc: 'Strong coverage across Asia, Europe, Americas, and Middle East.',
      predictableSchedules: 'Predictable Schedules',
      predictableSchedulesDesc: 'Regular cut-offs and sailings to plan production and delivery.',
      howItWorks: 'How LCL Works',
      step: 'Step',
      step1Title: 'Cargo Receipt at CFS',
      step1Note: 'Deliver cargo to our consolidation warehouse (CFS) before cut-off.',
      step2Title: 'Stuffing & Documentation',
      step2Note: 'We sort, label, and stuff consolidated containers; documents verified.',
      step3Title: 'Sailing & Deconsolidation',
      step3Note: 'Container sails to destination; we deconsolidate at destination CFS.',
      step4Title: 'Pickup / Delivery',
      step4Note: 'Collect cargo or arrange last-mile to your door.',
      includedServices: 'Included Services',
      service1: 'Origin CFS handling and export documentation',
      service2: 'Consolidation and destination deconsolidation',
      service3: 'Customs clearance options and delivery coordination',
      service4: 'Tracking visibility and POD',
      transitTimes: 'Typical Transit Times',
      asiaUSAEU: 'Asia ➜ USA/EU',
      asiaUSAEUTime: '25 - 40 days',
      asiaUSAEUNote: 'Varies by lane and consolidation hub',
      intraAsia: 'Intra-Asia',
      intraAsiaTime: '8 - 18 days',
      intraAsiaNote: 'Frequent feeder services',
      asiaMiddleEast: 'Asia ➜ Middle East',
      asiaMiddleEastTime: '14 - 25 days',
      asiaMiddleEastNote: 'Strong hub connectivity',
      transitNote: 'Note: LCL timing depends on consolidation schedules and deconsolidation times.',
      contactForLCL: 'Contact Us for LCL',
      tellUsCargo: 'Tell us your cargo details and we\'ll find the best LCL route.',
    },
    // Footer
    footer: {
      tagline: 'Reliable logistics solutions from Thailand to the world.',
      quickLinks: 'Quick Links',
      aboutUs: 'About Us',
      customerPortal: 'Customer Portal',
      employeePortal: 'Employee Portal',
      allRights: 'All rights reserved.',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
    },
    // Form
    form: {
      verifyCode: 'Verify Code',
      refreshCode: 'Refresh code',
      sending: 'Sending...',
      send: 'Send',
    },
    // Common Buttons & Actions
    buttons: {
      learnMore: 'Learn More',
      readMore: 'Read More',
      viewAll: 'View All',
      back: 'Back',
      next: 'Next',
      previous: 'Previous',
    },
    // News Page
    news: {
      title: 'News & Updates',
      subtitle: 'Stay informed about the latest from Asian Shipping Thailand',
      loading: 'Loading news...',
      noNews: 'No News Yet',
      noNewsDesc: 'Check back soon for updates and announcements.',
      readMore: 'Read More',
    },
  },
  th: {
    // Common
    common: {
      home: 'หน้าแรก',
      about: 'เกี่ยวกับเรา',
      services: 'บริการ',
      contact: 'ติดต่อเรา',
      getQuote: 'ขอใบเสนอราคา',
      trackShipment: 'ติดตามพัสดุ',
      login: 'เข้าสู่ระบบ',
      logout: 'ออกจากระบบ',
      submit: 'ส่ง',
      cancel: 'ยกเลิก',
      close: 'ปิด',
      save: 'บันทึก',
      delete: 'ลบ',
      edit: 'แก้ไข',
      view: 'ดู',
      search: 'ค้นหา',
      loading: 'กำลังโหลด...',
      welcome: 'ยินดีต้อนรับ',
    },
    // Home page
    home: {
      hero: 'พันธมิตรด้านโลจิสติกส์ที่คุณไว้วางใจทั่วเอเชีย',
      subtitle: 'โซลูชันการจัดส่งที่ราบรื่นเชื่อมต่อไทยกับทุกมุมเอเชีย',
      slide1Title: 'โซลูชันโลจิสติกส์ระดับโลก',
      slide1Subtitle: 'เชื่อมต่อธุรกิจของคุณสู่โลกด้วยบริการขนส่งทางอากาศและทางทะเลที่ราบรื่น',
      slide2Title: 'การจัดส่งที่เชื่อถือได้และรวดเร็ว',
      slide2Subtitle: 'อัตราการจัดส่งตรงเวลา 99.5% ทั่ว 200+ ท่าเรือและสนามบินทั่วโลก',
      slide3Title: 'เครือข่ายขนส่งสินค้าทั่วโลก',
      slide3Subtitle: 'ได้รับความไว้วางใจจากธุรกิจทั่วโลกสำหรับความต้องการด้านการขนส่งและโลจิสติกส์',
      whyChoose: 'ทำไมต้องเลือกเรา?',
      trackYourShipment: 'ติดตามพัสดุของคุณ',
      enterTracking: 'กรอกหมายเลขติดตาม',
      track: 'ติดตาม',
      ourServices: 'บริการของเรา',
      testimonials: 'ความคิดเห็นลูกค้า',
      readyToShip: 'พร้อมจัดส่ง?',
      getStarted: 'เริ่มต้นใช้โซลูชันโลจิสติกส์ที่เชื่อถือได้ของเราวันนี้',
      contactUsToday: 'ติดต่อเราวันนี้และสัมผัสโซลูชันโลจิสติกส์ระดับโลกด้วยราคาที่แข่งขันได้',
      contactUsNow: 'ติดต่อเราเลย',
      shipmentsDelivered: 'พัสดุที่จัดส่ง',
      countriesServed: 'ประเทศที่ให้บริการ',
      yearsExperience: 'ปีของประสบการณ์',
      satisfactionRate: 'อัตราความพึงพอใจ',
      secureTitle: 'ปลอดภัยและมั่นคง',
      secureDesc: 'มาตรการรักษาความปลอดภัยขั้นสูงและความคุ้มครองประกันเพื่อความสบายใจ',
      trackingTitle: 'ติดตามแบบเรียลไทม์',
      trackingDesc: 'ติดตามพัสดุของคุณตลอด 24/7 ด้วยระบบติดตามขั้นสูงของเรา',
      supportTitle: 'การสนับสนุนจากผู้เชี่ยวชาญ',
      supportDesc: 'ทีมบริการลูกค้าเฉพาะทางพร้อมให้บริการตลอดเวลา',
      coverageTitle: 'ความครอบคลุมทั่วโลก',
      coverageDesc: '200+ ท่าเรือและสนามบินทั่วเอเชียและอื่นๆ',
      globalNetwork: 'เครือข่ายโลกของเรา',
      partnerNetwork: 'เครือข่ายพันธมิตรใน 5 ทวีป',
      airFreight: 'ขนส่งทางอากาศ',
      airFreightDesc: 'บริการขนส่งสินค้าทางอากาศที่รวดเร็วและเชื่อถือได้ในราคาแข่งขัน',
      seaFreightFCL: 'ขนส่งทางทะเล FCL',
      seaFreightFCLDesc: 'การจัดส่งตู้เต็มตู้สำหรับปริมาณมาก',
      seaFreightLCL: 'ขนส่งทางทะเล LCL',
      seaFreightLCLDesc: 'บริการตู้รวมที่ประหยัดต้นทุน',
      warehousing: 'คลังสินค้า',
      warehousingDesc: 'โซลูชันการจัดเก็บและการจัดการสินค้าคงคลังที่ปลอดภัย',
      weeklyFlights: 'เที่ยวบินรายสัปดาห์',
      globalPorts: 'ท่าเรือทั่วโลก',
      happyClients: 'ลูกค้าที่พึงพอใจ',
      onTimeRate: 'อัตราตรงเวลา',
      expressDelivery: 'จัดส่งด่วน',
      realTimeTracking: 'ติดตามแบบเรียลไทม์',
      customsSupport: 'สนับสนุนด้านศุลกากร',
      containerOptions: 'ตัวเลือกตู้คอนเทนเนอร์',
      competitiveRates: 'อัตราแข่งขัน',
      globalNetworkFeature: 'เครือข่ายโลก',
      flexibleScheduling: 'ตารางเวลาที่ยืดหยุ่น',
      consolidation: 'รวมพัสดุ',
      weeklyDepartures: 'ออกเดินทางรายสัปดาห์',
      security247: 'รักษาความปลอดภัย 24/7',
      climateControl: 'ควบคุมอุณหภูมิ',
      inventoryTracking: 'ติดตามสินค้าคงคลัง',
      comprehensiveSolutions: 'โซลูชันโลจิสติกส์ที่ครอบคลุมออกแบบมาเพื่อความต้องการทางธุรกิจของคุณ',
      viewAllServices: 'ดูบริการทั้งหมด',
      industryLeading: 'โซลูชันโลจิสติกส์ชั้นนำในอุตสาหกรรมที่มีความน่าเชื่อถือที่ไม่มีใครเทียบ',
      learnMoreAboutUs: 'เรียนรู้เพิ่มเติมเกี่ยวกับเรา',
      callUs: 'โทรหาเรา',
      emailUs: 'อีเมลหาเรา',
      businessHours: 'เวลาทำการ',
      monFri: 'จันทร์-ศุกร์: 9:00-18:00 น.',
      sat: 'เสาร์: 10:00-14:00 น.',
      sun: 'อาทิตย์: ปิด',
    },
    // Services
    services: {
      airfreight: 'ขนส่งทางอากาศ',
      airfreightDesc: 'บริการขนส่งสินค้าทางอากาศที่รวดเร็วและเชื่อถือได้ทั่วเอเชีย',
      fcl: 'ตู้เต็มตู้ (FCL)',
      fclDesc: 'การจัดส่งตู้คอนเทนเนอร์เต็มสำหรับสินค้าปริมาณมาก',
      lcl: 'ตู้รวม (LCL)',
      lclDesc: 'การจัดส่งประหยัดสำหรับสินค้าขนาดเล็ก',
      customs: 'ผ่านพิธีการศุลกากร',
      customsDesc: 'จัดการเอกสารศุลกากรอย่างเชี่ยวชาญ',
      warehousing: 'คลังสินค้า',
      warehousingDesc: 'บริการเก็บและจัดจำหน่ายที่ปลอดภัย',
      insurance: 'ประกันสินค้า',
      insuranceDesc: 'การคุ้มครองที่ครอบคลุมสำหรับการจัดส่งของคุณ',
    },
    // Contact
    contact: {
      getInTouch: 'ติดต่อเรา',
      requestQuote: 'ขอใบเสนอราคา',
      name: 'ชื่อของคุณ',
      email: 'อีเมล',
      phone: 'เบอร์โทรศัพท์',
      company: 'ชื่อบริษัท',
      service: 'บริการที่ต้องการ',
      selectService: 'เลือกบริการ',
      message: 'ข้อความ',
      sendMessage: 'ส่งข้อความ',
      contactInfo: 'ข้อมูลติดต่อ',
      officeHours: 'เวลาทำการ',
      mondayFriday: 'จันทร์ - ศุกร์: 9:00 - 18:00 น.',
      saturday: 'เสาร์: 9:00 - 13:00 น.',
      sunday: 'อาทิตย์: ปิด',
      helpLogistics: 'เราพร้อมช่วยเหลือคุณในทุกความต้องการด้านโลจิสติกส์',
    },
    // Portal
    portal: {
      customerPortal: 'พอร์ทัลลูกค้า',
      myShipments: 'พัสดุของฉัน',
      trackShipment: 'ติดตามพัสดุ',
      profile: 'โปรไฟล์',
      settings: 'การตั้งค่า',
      shipmentDetails: 'รายละเอียดการจัดส่ง',
      status: 'สถานะ',
      origin: 'ต้นทาง',
      destination: 'ปลายทาง',
      weight: 'น้ำหนัก',
      eta: 'เวลาถึงโดยประมาณ',
      viewTracking: 'ดูการติดตาม',
    },
    // Admin Portal
    admin: {
      adminPortal: 'พอร์ทัลแอดมิน',
      dashboard: 'แดชบอร์ด',
      manageShipments: 'จัดการพัสดุ',
      addShipment: 'เพิ่มพัสดุ',
      customerQuotes: 'ใบเสนอราคาลูกค้า',
      documents: 'เอกสาร',
      database: 'ฐานข้อมูล',
      totalShipments: 'พัสดุทั้งหมด',
      activeShipments: 'พัสดุที่ใช้งาน',
      recentQuotes: 'ใบเสนอราคาล่าสุด',
      quoteRequests: 'คำขอใบเสนอราคา',
      recentEmails: 'อีเมลล่าสุด',
      composeEmail: 'เขียนอีเมล',
      newRequests: 'คำขอใหม่',
      responded: 'ตอบกลับแล้ว',
      pending: 'รอดำเนินการ',
      remove: 'ลบ',
      removeSelected: 'ลบที่เลือก',
      permanentDelete: 'ลบถาวร',
      viewRawJson: 'ดูข้อมูล JSON',
    },
    // Tracking
    tracking: {
      trackYourShipment: 'ติดตามพัสดุของคุณ',
      trackingNumber: 'หมายเลขติดตาม',
      shipmentNotFound: 'ไม่พบพัสดุ',
      trackingHistory: 'ประวัติการติดตาม',
      current: 'ปัจจุบัน',
      serviceType: 'ประเภทบริการ',
      bookingDate: 'วันที่จอง',
      estimatedDelivery: 'วันที่จัดส่งโดยประมาณ',
    },
    // About Page
    about: {
      title: 'เกี่ยวกับ Asian Shipping Thailand',
      subtitle: 'พันธมิตรด้านโลจิสติกส์ที่เชื่อถือได้ของประเทศไทยสำหรับการขนส่งและศุลกากรตั้งแต่ปี 2545',
      yearsExp: 'ปีของประสบการณ์',
      regionalFocus: 'เน้นภูมิภาค',
      fastCustoms: 'ผ่านพิธีการศุลกากรเร็ว',
      deliveryGuarantee: 'รับประกันการจัดส่ง',
      ourStory: 'เรื่องราวของเรา',
      storyP1: 'ก่อตั้งในปี 2545 บริษัท Asian Shipping (Thailand) จำกัด เริ่มต้นด้วยพันธกิจที่เรียบง่าย: ทำให้การขนส่งระหว่างประเทศเข้าถึงได้และเชื่อถือได้สำหรับธุรกิจทุกขนาด สิ่งที่เริ่มต้นเป็นธุรกิจขนส่งสินค้าขนาดเล็กในกรุงเทพฯ ได้เติบโตเป็นพันธมิตรด้านโลจิสติกส์ที่เชื่อถือได้ที่ให้บริการลูกค้าทั่วเอเชียและต่างประเทศ',
      storyP2: 'ในฐานะนายหน้าศุลกากรที่ผ่านการรับรองในประเทศไทย เราเชี่ยวชาญในการผ่านพิธีการศุลกากรทั้งสินค้าทั่วไปและสินค้าอันตราย ความเชี่ยวชาญของเราในบริการขนส่งทางอากาศ ทะเล และทางบก รวมกับการรับประกันการจัดส่งภายในหนึ่งวันสำหรับการนำเข้า ทำให้เราเป็นผู้ให้บริการที่เร็วที่สุดในกลุ่มผู้ขนส่งท้องถิ่น',
      storyP3: 'เราไม่ได้แค่ขนย้ายสินค้า—เราคือพันธมิตรด้านโลจิสติกส์ของคุณ มุ่งมั่นในการยื่นเอกสารที่รวดเร็วและเชื่อถือได้ บริการจากประตูสู่ประตูที่ราบรื่น และทำให้การดำเนินธุรกิจของคุณราบรื่นทั่วประเทศไทยและเอเชีย',
      certificationsTitle: 'ใบรับรองและสมาชิกภาพ',
      certificationsSubtitle: 'เชื่อถือได้ ได้รับการรับรอง และมีคุณสมบัติในการให้บริการคุณ',
      certifications: 'ใบรับรอง',
      customsBrokerage: 'นายหน้าศุลกากร',
      customsDesc: 'บริษัท Asian Shipping (Thailand) จำกัด เป็นนายหน้าศุลกากรที่ผ่านการรับรองในประเทศไทย เราเชี่ยวชาญในการผ่านพิธีการศุลกากรทั้งสินค้าทั่วไปและสินค้าอันตราย การจัดส่งภายในหนึ่งวันสำหรับการนำเข้าและการยื่นเอกสารภายในหนึ่งวันสำหรับการส่งออก',
      customsMission: 'การยื่นเอกสารที่รวดเร็วและเชื่อถือได้คือพันธกิจของเรา',
      doorToDoor: 'บริการจากประตูสู่ประตูและการขนส่งภายในประเทศ',
      doorToDoorDesc: 'เนื่องจากผลงานที่ดีที่สุดของเราในด้านนายหน้าศุลกากร เราได้รับความไว้วางใจให้เป็นผู้ให้บริการจากประตูสู่ประตูที่เร็วที่สุดในประเทศไทยในกลุ่มผู้ขนส่งท้องถิ่น Asian รับประกันการจัดส่งภายในหนึ่งวันให้กับลูกค้าทุกรายในประเทศไทย',
      oneDayGuarantee: 'รับประกันการจัดส่งภายในหนึ่งวันในประเทศไทย',
      meetTeam: 'พบทีมของเรา',
      teamSubtitle: 'ผู้เชี่ยวชาญที่มีประสบการณ์ทุ่มเทเพื่อความสำเร็จของคุณ',
      coreValues: 'คุณค่าหลักของเรา',
      valuesSubtitle: 'หลักการที่นำทางทุกสิ่งที่เราทำ',
      reliability: 'ความน่าเชื่อถือ',
      reliabilityDesc: 'เราทำตามสัญญาด้วยบริการที่สม่ำเสมอและเชื่อถือได้ที่คุณไว้วางใจได้',
      speed: 'ความเร็ว',
      speedDesc: 'การประมวลผลและเวลาขนส่งที่รวดเร็วเพื่อให้ธุรกิจของคุณเดินหน้าต่อไป',
      security: 'ความปลอดภัย',
      securityDesc: 'สินค้าของคุณได้รับการปกป้องด้วยประกันภัยที่ครอบคลุมและการจัดการที่ปลอดภัย',
      partnership: 'ความเป็นหุ้นส่วน',
      partnershipDesc: 'เราทำงานเป็นพันธมิตรด้านโลจิสติกส์ของคุณ ไม่ใช่แค่ผู้ให้บริการ',
      readyToShip: 'พร้อมที่จะจัดส่งกับเรา?',
      joinBusiness: 'เข้าร่วมกับธุรกิจหลายพันรายที่ไว้วางใจ asianshippingthai สำหรับความต้องการด้านการจัดส่งของพวกเขา',
      getStarted: 'เริ่มต้น',
      viewServices: 'ดูบริการ',
    },
    // Services Pages
    servicesPage: {
      ourServices: 'บริการของเรา',
      professionalFreight: 'โซลูชันการขนส่งสินค้าระดับมืออาชีพ',
      contactUs: 'ติดต่อเรา',
      exploreFeat: 'สำรวจคุณสมบัติ',
      airfreightServices: 'บริการขนส่งทางอากาศ',
      fastReliableAir: 'ขนส่งสินค้าทางอากาศที่รวดเร็วและเชื่อถือได้',
      deliverWorldwide: 'เราจัดส่งสินค้าทั่วโลกด้วยความรวดเร็วและแม่นยำผ่านเครือข่ายผู้ให้บริการขนส่งทางอากาศที่กว้างขวางของเรา',
      seafreightFCL: 'บริการขนส่งทางทะเล: FCL',
      fullContainerLoad: 'ตู้เต็มตู้',
      fullContainerShipping: 'บริการขนส่งตู้เต็มตู้สำหรับการขนส่งทางทะเลขนาดใหญ่ด้วยตัวเลือกที่ยืดหยุ่น',
      seafreightLCL: 'บริการขนส่งทางทะเล: LCL',
      lessThanContainer: 'น้อยกว่าตู้เต็มตู้',
      costEffectiveSea: 'โซลูชันการขนส่งทางทะเลที่ประหยัดต้นทุนเหมาะสำหรับการจัดส่งขนาดเล็ก',
      expressDelivery: 'จัดส่งด่วน',
      realTimeTracking: 'ติดตามแบบเรียลไทม์',
      customsClearance: 'ผ่านพิธีการศุลกากร',
      doorToDoorService: 'บริการจากประตูสู่ประตู',
      containers2040: 'ตู้คอนเทนเนอร์ 20 และ 40 ฟุต',
      competitiveRates: 'อัตราแข่งขัน',
      globalNetwork: 'เครือข่ายโลก',
      dedicatedSupport: 'การสนับสนุนเฉพาะ',
      costEffective: 'ประหยัดต้นทุน',
      flexibleScheduling: 'ตารางเวลาที่ยืดหยุ่น',
      consolidation: 'รวมพัสดุ',
      weeklyDepartures: 'ออกเดินทางรายสัปดาห์',
      learnMore: 'เรียนรู้เพิ่มเติม',
    },
    // Airfreight Page
    airfreight: {
      title: 'บริการขนส่งทางอากาศ',
      subtitle: 'โซลูชันการขนส่งสินค้าทางอากาศที่รวดเร็วและเชื่อถือได้พร้อมการติดตามที่ครบถ้วนและการจัดการศุลกากรโดยผู้เชี่ยวชาญ',
      whyShipByAir: 'ทำไมต้องขนส่งทางอากาศกับเรา',
      expressEconomy: 'ด่วนและประหยัด',
      expressDesc: 'เที่ยวบินถัดไป ด่วน และเลื่อนเวลาได้เพื่อให้เหมาะกับงบประมาณและกำหนดเวลาของคุณ',
      liveTracking: 'ติดตามสด',
      liveTrackingDesc: 'อัปเดตจุดสำคัญแบบเรียลไทม์ตั้งแต่รับสินค้าจนถึงจัดส่งพร้อมการแจ้งเตือนเชิงรุก',
      customsClearance: 'ผ่านพิธีการศุลกากร',
      customsDesc: 'เอกสารและการเป็นนายหน้าแบบครบวงจรเพื่อให้การขนส่งดำเนินต่อไปที่ชายแดน',
      doorToDoor: 'จากประตูสู่ประตู',
      doorToDoorDesc: 'รับสินค้า ขนส่งระหว่างทาง และไมล์สุดท้ายจัดการอย่างราบรื่นโดยทีมของเรา',
      serviceOptions: 'ตัวเลือกบริการ',
      serviceOptionsDesc: 'เรามีโปรไฟล์บริการที่ยืดหยุ่น: เที่ยวบินถัดไป ด่วน มาตรฐาน และเลื่อนเวลา ไม่ว่าคุณจะให้ความสำคัญกับความเร็วหรือต้นทุน ทีมของเราจะวางแผนเส้นทางและการผสมผสานผู้ให้บริการที่เหมาะสมที่สุดสำหรับสินค้าของคุณ',
      serviceList1: 'รับสินค้า รวมสินค้า จองสายการบิน และจัดส่งไมล์สุดท้าย',
      serviceList2: 'การจัดการสินค้าอันตรายและการสนับสนุนเอกสาร',
      serviceList3: 'ตัวเลือกควบคุมอุณหภูมิตามคำขอ',
      serviceList4: 'ความคุ้มครองประกันภัยและหลักฐานการจัดส่ง (POD)',
      whatWeHandle: 'สิ่งที่เราจัดการ',
      electronics: 'อิเล็กทรอนิกส์และชิ้นส่วน',
      apparel: 'เสื้อผ้าและสิ่งทอ',
      automotive: 'ชิ้นส่วนยานยนต์',
      medical: 'การแพทย์และเภสัชกรรม',
      perishables: 'สินค้าเน่าเสียง่ายและเครื่องดื่ม',
      industrial: 'เครื่องมืออุตสาหกรรมและเครื่องจักร',
      documents: 'เอกสารและสินค้ามีค่าสูง',
      transitTimes: 'เวลาขนส่งโดยทั่วไป',
      asiaUSAEU: 'เอเชีย ➜ USA/EU',
      asiaUSAEUTime: '2 - 5 วัน',
      asiaUSAEUNote: 'บริการโดยตรงและรวมสินค้า',
      intraAsia: 'ภายในเอเชีย',
      intraAsiaTime: '1 - 3 วัน',
      intraAsiaNote: 'ความถี่ในการออกเดินทางสูง',
      asiaMiddleEast: 'เอเชีย ➜ ตะวันออกกลาง',
      asiaMiddleEastTime: '2 - 4 วัน',
      asiaMiddleEastNote: 'การเชื่อมต่อฮับที่แข็งแกร่ง',
      transitNote: 'หมายเหตุ: เวลาขนส่งเป็นการประมาณและอาจแตกต่างกันไปตามผู้ให้บริการและฤดูกาล',
      readyToMove: 'พร้อมที่จะขนส่งสินค้าของคุณหรือยัง?',
      tellUsAbout: 'บอกเราเกี่ยวกับการจัดส่งของคุณและเราจะให้โซลูชันการขนส่งทางอากาศที่ดีที่สุด',
    },
    // FCL Page
    fcl: {
      title: 'FCL (ตู้เต็มตู้)',
      subtitle: 'โซลูชันตู้คอนเทนเนอร์เต็มทางทะเลที่เชื่อถือได้พร้อมตารางเวลารายสัปดาห์และอัตราแข่งขัน',
      whyChooseFCL: 'ทำไมต้องเลือก FCL กับเรา',
      containers: 'ตู้คอนเทนเนอร์ 20\' และ 40\'',
      containersDesc: 'มาตรฐาน ไฮคิวบ์ และอุปกรณ์พิเศษตามความต้องการของสินค้า',
      globalNetwork: 'เครือข่ายโลก',
      globalNetworkDesc: 'การเดินเรือรายสัปดาห์ที่เชื่อถือได้กับผู้ให้บริการชั้นนำและความครอบคลุมท่าเรือที่แข็งแกร่ง',
      flexibleRouting: 'เส้นทางที่ยืดหยุ่น',
      flexibleRoutingDesc: 'บริการโดยตรง ผ่านการถ่ายลำ และพรีเมียมสำหรับสินค้าที่มีเวลาจำกัด',
      secureHandling: 'การจัดการที่ปลอดภัย',
      secureHandlingDesc: 'ความปลอดภัยของตู้ที่ปิดผนึกและประกันสินค้าเป็นตัวเลือก',
      containerOptions: 'ตัวเลือกตู้คอนเทนเนอร์',
      container20: 'มาตรฐาน 20\'',
      container40: 'มาตรฐาน 40\'',
      container40HC: 'ไฮคิวบ์ 40\'',
      specialEquipment: 'อุปกรณ์พิเศษ',
      openTopFlatRack: 'Open Top / Flat Rack',
      approx: 'ประมาณ',
      includedServices: 'บริการที่รวมอยู่',
      service1: 'รับสินค้า บรรจุ VGM เอกสาร และผ่านพิธีการศุลกากรส่งออก',
      service2: 'การจองผู้ให้บริการและการปกป้องพื้นที่ในช่วงฤดูกาลที่มีผู้ใช้มาก',
      service3: 'การสนับสนุน DO/ISF ปลายทางและการประสานงานการจัดส่ง',
      service4: 'ตัวเลือกประกันและการมองเห็นการจัดส่ง',
      transitTimes: 'เวลาขนส่งโดยทั่วไป',
      asiaUSAWC: 'เอเชีย ➜ USA (ฝั่งตะวันตก)',
      asiaUSAWCTime: '14 - 20 วัน',
      asiaUSAWCNote: 'การเดินเรือโดยตรงไปฝั่งตะวันตก',
      asiaUSAEC: 'เอเชีย ➜ USA (ฝั่งตะวันออก)',
      asiaUSAECTime: '25 - 35 วัน',
      asiaUSAECNote: 'ผ่านปานามาหรือสุเอซ',
      asiaEurope: 'เอเชีย ➜ ยุโรป',
      asiaEuropeTime: '25 - 35 วัน',
      asiaEuropeNote: 'สายการเรือหลักและพันธมิตร',
      transitNote: 'หมายเหตุ: เวลาขนส่งแตกต่างกันไปตามผู้ให้บริการ ความแออัดของท่าเรือ และฤดูกาล',
      contactForFCL: 'ติดต่อเราสำหรับ FCL',
      tellUsOrigin: 'บอกเราต้นทาง ปลายทาง และขนาดตู้เพื่อเริ่มต้น',
    },
    // LCL Page
    lcl: {
      title: 'LCL (น้อยกว่าตู้เต็มตู้)',
      subtitle: 'การขนส่งทางทะเลที่ประหยัดต้นทุนสำหรับสินค้าขนาดเล็กพร้อมตารางเวลารายสัปดาห์ที่เชื่อถือได้',
      whyShipLCL: 'ทำไมต้องขนส่ง LCL กับเรา',
      sharedSpace: 'พื้นที่ใช้ร่วมกัน ต้นทุนต่ำกว่า',
      sharedSpaceDesc: 'จ่ายเฉพาะพื้นที่ที่คุณใช้ด้วยการรวมสินค้ารายสัปดาห์ที่เชื่อถือได้',
      secureConsolidation: 'การรวมสินค้าที่ปลอดภัย',
      secureConsolidationDesc: 'การจัดการอย่างระมัดระวังที่ CFS ต้นทางพร้อมมาตรฐานการติดฉลากและบรรจุที่ชัดเจน',
      extensiveLanes: 'เส้นทางที่กว้างขวาง',
      extensiveLanesDesc: 'ความครอบคลุมที่แข็งแกร่งทั่วเอเชีย ยุโรป อเมริกา และตะวันออกกลาง',
      predictableSchedules: 'ตารางเวลาที่คาดการณ์ได้',
      predictableSchedulesDesc: 'กำหนดเวลาปิดรับและการเดินเรือที่สม่ำเสมอเพื่อวางแผนการผลิตและจัดส่ง',
      howItWorks: 'LCL ทำงานอย่างไร',
      step: 'ขั้นตอนที่',
      step1Title: 'รับสินค้าที่ CFS',
      step1Note: 'ส่งสินค้าไปยังคลังสินค้ารวมของเรา (CFS) ก่อนกำหนดเวลาปิดรับ',
      step2Title: 'บรรจุและเอกสาร',
      step2Note: 'เราจัดเรียง ติดฉลาก และบรรจุตู้รวม; ตรวจสอบเอกสาร',
      step3Title: 'การเดินเรือและการแยกสินค้า',
      step3Note: 'ตู้เดินทางไปยังปลายทาง; เราแยกสินค้าที่ CFS ปลายทาง',
      step4Title: 'รับสินค้า / จัดส่ง',
      step4Note: 'รับสินค้าหรือจัดการไมล์สุดท้ายถึงประตูบ้านคุณ',
      includedServices: 'บริการที่รวมอยู่',
      service1: 'การจัดการ CFS ต้นทางและเอกสารส่งออก',
      service2: 'การรวมสินค้าและการแยกสินค้าปลายทาง',
      service3: 'ตัวเลือกการผ่านศุลกากรและการประสานงานการจัดส่ง',
      service4: 'การมองเห็นการติดตามและ POD',
      transitTimes: 'เวลาขนส่งโดยทั่วไป',
      asiaUSAEU: 'เอเชีย ➜ USA/EU',
      asiaUSAEUTime: '25 - 40 วัน',
      asiaUSAEUNote: 'แตกต่างกันไปตามเส้นทางและฮับรวมสินค้า',
      intraAsia: 'ภายในเอเชีย',
      intraAsiaTime: '8 - 18 วัน',
      intraAsiaNote: 'บริการฟีดเดอร์บ่อยครั้ง',
      asiaMiddleEast: 'เอเชีย ➜ ตะวันออกกลาง',
      asiaMiddleEastTime: '14 - 25 วัน',
      asiaMiddleEastNote: 'การเชื่อมต่อฮับที่แข็งแกร่ง',
      transitNote: 'หมายเหตุ: เวลา LCL ขึ้นอยู่กับตารางการรวมสินค้าและเวลาในการแยกสินค้า',
      contactForLCL: 'ติดต่อเราสำหรับ LCL',
      tellUsCargo: 'บอกรายละเอียดสินค้าของคุณและเราจะหาเส้นทาง LCL ที่ดีที่สุด',
    },
    // Footer
    footer: {
      tagline: 'โซลูชันโลจิสติกส์ที่เชื่อถือได้จากประเทศไทยสู่โลก',
      quickLinks: 'ลิงก์ด่วน',
      aboutUs: 'เกี่ยวกับเรา',
      customerPortal: 'พอร์ทัลลูกค้า',
      employeePortal: 'พอร์ทัลพนักงาน',
      allRights: 'สงวนลิขสิทธิ์',
      privacyPolicy: 'นโยบายความเป็นส่วนตัว',
      termsOfService: 'ข้อกำหนดการใช้บริการ',
    },
    // Form
    form: {
      verifyCode: 'รหัสยืนยัน',
      refreshCode: 'รีเฟรชรหัส',
      sending: 'กำลังส่ง...',
      send: 'ส่ง',
    },
    // Common Buttons & Actions
    buttons: {
      learnMore: 'เรียนรู้เพิ่มเติม',
      readMore: 'อ่านเพิ่มเติม',
      viewAll: 'ดูทั้งหมด',
      back: 'กลับ',
      next: 'ถัดไป',
      previous: 'ก่อนหน้า',
    },
    // News Page
    news: {
      title: 'ข่าวสารและอัพเดท',
      subtitle: 'ติดตามข่าวสารล่าสุดจาก Asian Shipping Thailand',
      loading: 'กำลังโหลดข่าวสาร...',
      noNews: 'ยังไม่มีข่าวสาร',
      noNewsDesc: 'กรุณากลับมาตรวจสอบอีกครั้งเพื่อดูข่าวสารและประกาศใหม่',
      readMore: 'อ่านเพิ่มเติม',
    },
  },
};
